# Global Variables
CONFIG_PROFILE = "DEFAULT"
NAMESPACE = "axbpjkug04ct"
BUCKET_NAME = "target-bucket"
OBJECT_NAME = "testdirectory/part-00000-a2676ae3-39e8-420f-a7fe-e0843e9fea0e-c000.json"
COMPARTMENT_ID = "ocid1.compartment.oc1..aaaaaaaalnzl6zjv5aarhl32amczyeqwl7ahxnzqxwjpzppb74e7ubouzn4a"
SESSION_ID = "abc123"
